# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 20:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo', '0027_auto_20160909_1703'),
        ('fitbit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntradayData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(max_length=40)),
                ('record_date', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('ext_value', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='apidata',
            name='ext_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intradaydata',
            name='api_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitbit.ApiData'),
        ),
        migrations.AddField(
            model_name='intradaydata',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intradaydata',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Member'),
        ),
    ]
