# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='languages',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='mobile_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='next_appt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='office_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='social',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='specialty',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='zip',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
