# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0008_auto_20160905_1700'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='demo_user_profile',
        ),
    ]
