# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0013_member_picture_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=40)),
                ('start_date', models.DateField(default='1900-01-01')),
                ('end_date', models.DateField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='provider_member',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare.Member'),
        ),
        migrations.AddField(
            model_name='provider_member',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare.Provider'),
        ),
        migrations.AddField(
            model_name='provider',
            name='members',
            field=models.ManyToManyField(through='healthcare.Provider_Member', to='healthcare.Member'),
        ),
    ]
