# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0014_auto_20160907_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providermember',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='providermember',
            name='start_date',
            field=models.DateField(default='1970-01-01'),
        ),
    ]
