# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0018_auto_20160907_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='picture_path',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
