# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0023_auto_20160908_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_medical',
            name='measure_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
