# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0026_auto_20160909_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='query_url',
            new_name='data',
        ),
        migrations.AddField(
            model_name='message',
            name='smssid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='smsstatus',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
