# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0028_rx_claim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rx_claim',
            name='member',
        ),
        migrations.RemoveField(
            model_name='rx_claim',
            name='provider',
        ),
        migrations.DeleteModel(
            name='Rx_Claim',
        ),
    ]
