# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0030_druginfo_pharmacy_rx_claim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rx_claim',
            name='druginfo',
        ),
        migrations.RemoveField(
            model_name='rx_claim',
            name='member',
        ),
        migrations.RemoveField(
            model_name='rx_claim',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='rx_claim',
            name='provider',
        ),
        migrations.AddField(
            model_name='provider',
            name='provider_type',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.DeleteModel(
            name='DrugInfo',
        ),
        migrations.DeleteModel(
            name='Pharmacy',
        ),
        migrations.DeleteModel(
            name='Rx_Claim',
        ),
    ]
