# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0032_auto_20160918_1335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='County_Data',
        ),
        migrations.DeleteModel(
            name='CountyMetrics',
        ),
        migrations.RenameField(
            model_name='countymetricwidget',
            old_name='val1_col',
            new_name='val1_ref',
        ),
        migrations.RenameField(
            model_name='countymetricwidget',
            old_name='val2_col',
            new_name='val2_ref',
        ),
        migrations.RenameField(
            model_name='countymetricwidget',
            old_name='val3_col',
            new_name='val3_ref',
        ),
    ]
