# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0045_auto_20160922_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='address',
            field=models.CharField(default='a', max_length=40),
            preserve_default=False,
        ),
    ]
