# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0047_county_widget_us_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='county_widget',
            name='us_str',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='county_widget',
            name='us_val_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='county_widget',
            name='val1_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='county_widget',
            name='val2_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='county_widget',
            name='val3_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
