# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='picture_path',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
