# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0015_auto_20160907_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providermember',
            name='start_date',
            field=models.DateField(),
        ),
    ]
