# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0021_auto_20160908_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermedical',
            name='value_1_alert_lo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='membermedical',
            name='value_1_tgt_lo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='membermedical',
            name='value_2_alert_hi',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='membermedical',
            name='value_2_tgt_hi',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='membermedical',
            name='measure_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
