# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0035_auto_20160919_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countydata',
            name='county',
            field=models.CharField(max_length=40),
        ),
    ]
