# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0042_countywidget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countywidget',
            name='measure_name',
            field=models.CharField(max_length=40),
        ),
    ]
