# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0046_pharmacy_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='countywidget',
            name='us_val',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
