# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0049_auto_20160923_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countydata',
            name='unins_1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
