# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0050_auto_20160923_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='pharmacy_chain',
            new_name='chain',
        ),
        migrations.RenameField(
            model_name='pharmacy',
            old_name='pharmacy_name',
            new_name='name',
        ),
    ]
