# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0051_auto_20160925_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='membernotification',
            name='ref_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membernotification',
            name='ref_table',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
